#!/usr/bin/env python3

import fileinput


def main():
	lines = list(map(str.strip, list(fileinput.input())))
	longest_line = max(map(len, lines))
	mid = int(longest_line / 2)

	for line in list(lines):
		start = mid - int(len(line) / 2)
		print(" " * start + line)


if __name__ == '__main__':
	main()
