#!/usr/bin/env python3

import os
import sys


def main():
	if len(sys.argv) != 2:
		print("Usage: {} path".format(sys.argv[0]), file=sys.stderr)
		exit(1)
	print(os.path.normpath(sys.argv[1]))


if __name__ == '__main__':
	main()
